### ISSUE TITLE
Feature: support for npx command in node_module/.bin ?

### ISSUE THREAD

**Issue by eki3z** [mohkale/flymake-rest#36]
in the :pre-let and :pre-check section, would it be possible to run in the project directory and check if npx command like
`npx eslint` or `npx oxlint` exists and calling ? I guess these command usually installed locally in project.

**Comment by mohkale** [comment]
I see no harm in adding a executable-find npx check within any npm based linters and running through that if it exists. I assume npx will use the node_modules folder for the current project if the package is not installed and otherwise have some flag to fail (instead of trying to install the checker) :thinking:.

**Comment by mohkale** [comment]
Closing. As discussed https://github.com/mohkale/flymake-collection/pull/39#discussion_r1650160584 this should be a more general solution than something in this package.
