### ISSUE TITLE
configure mypy CLI flags?

### ISSUE THREAD

**Issue by jgarte** [mohkale/flymake-rest#6]
Hi,

How can I configure the mypy cli flags/options?

Or, what is your approach?

**Comment by mohkale** [comment]
@jgarte 

Currently not supported but should be easy to add in. PRs are welcome. See [gcc](https://github.com/mohkale/flymake-collection/blob/cd2574574bda1f3d94007cdc3b7e0f8007d69716/src/checkers/flymake-collection-gcc.el#L34) for an example. Essentially create a new `defcustom` for the variable to set these flags in [flymake-collection-mypy](https://github.com/mohkale/flymake-collection/blob/cd2574574bda1f3d94007cdc3b7e0f8007d69716/src/checkers/flymake-collection-mypy.el) and then update the [:command option](https://github.com/mohkale/flymake-collection/blob/cd2574574bda1f3d94007cdc3b7e0f8007d69716/src/checkers/flymake-collection-mypy.el#L46) to use it just like in [gcc](https://github.com/mohkale/flymake-collection/blob/cd2574574bda1f3d94007cdc3b7e0f8007d69716/src/checkers/flymake-collection-gcc.el#L64). You'll probably want to convert flymake-collection-mypy to use a backtick list like gcc instead of the function call. Let me know if you have any issues with this.

**Comment by jgarte** [comment]
@mohkale 

Can this issue be closed now that #9 got merged?

**Comment by mohkale** [comment]
Yep. Now we've got `flymake-collection-mypy-args` to set this.
